// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantFinder.Api.Data;

#nullable disable

namespace RestaurantFinder.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260208222502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("RestaurantFinder.Api.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuisine")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriceCategory")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Budapest, Fő utca 1.",
                            Cuisine = "Hungarian",
                            Latitude = 47.497900000000001,
                            Longitude = 19.040199999999999,
                            Name = "Paprika Bistro",
                            PriceCategory = 2
                        },
                        new
                        {
                            Id = 2,
                            Address = "Budapest, Andrássy út 10.",
                            Cuisine = "Italian",
                            Latitude = 47.506,
                            Longitude = 19.065999999999999,
                            Name = "Trattoria Roma",
                            PriceCategory = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
